[package]
name = "letsbayes"
version = "0.1.4"
edition = "2021"

[dependencies]
statrs = "0.17.1"
emcee = "0.3.0"
polars = {version = '0.43.0', features = ["lazy"]}
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
